import Head from "next/head";
import { getAllPosts } from "../../lib/notionApi";
import SinglePost from "../../components/Post/SinglePost";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    // 60秒ごとに更新
    revalidate: 60,
  };
};

export default function Home({ allPosts }) {
  console.log(allPosts);

  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl front-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        {allPosts.map((post) => (
          <div className="mx-4">
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
            />
          </div>
        ))}
      </main>
    </div>
  );
}
